backend:
  name: git-gateway
  branch: main

media_folder: "assets/images" # Mesto gde će se čuvati slike koje ubaciš iz CMS-a
public_folder: "/assets/images"

collections:
  - name: "vesti"
    label: "Vesti"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Naslov Vesti", name: "title", widget: "string"}
      - {label: "Datum objave", name: "date", widget: "datetime"}
      - {label: "Kategorija", name: "category", widget: "select", options: ["Društvo", "Politika", "Biznis", "Kultura", "Sport", "Hronika", "Svet"]}
      - {label: "Glavna Vest (Slajder)", name: "glavna", widget: "boolean", default: false}
      - {label: "Istaknuta slika", name: "image", widget: "image"}
      - {label: "Tekst Vesti", name: "body", widget: "markdown"}
